#!/bin/bash

source Settings
echo $PathToLaunchers
echo "Availible launchers"
ls -f --color $PathToLaunchers
    echo "Which launcher would you like to use?"

    #checks input for Launcher
    read Launcher

    echo You have selected $Launcher !
    echo Starting Minecraft...

    #launches whatever was chosen
    java -jar $PathToLaunchers/$Launcher.jar