#!/bin/bash
cd
        echo ":: Creating temp folder..."
        mkdir linuxmcinputfix_temp
        cd linuxmcinputfix_temp
        echo ":: Downloading Lightweight java gaming library..."
        wget -nv http://downloads.sourceforge.net/project/java-game-lib/Official%20Releases/LWJGL%202.6/lwjgl-2.6.zip
        echo ":: Unzipping into temp folder..."
        unzip -q lwjgl*
        cd ~/linuxmcinputfix_temp/lwjgl-2.6/jar/
        echo ":: Copying files into Minecraft folder..."
        cp -fv jinput.jar ~/.minecraft/bin/
        cp -fv lwjgl.jar ~/.minecraft/bin/
        cp -fv lwjgl_util.jar ~/.minecraft/bin/

        cd ~/linuxmcinputfix_temp/lwjgl-2.6/native/linux/
        cp -fv libjinput-linux64.so ~/.minecraft/bin/natives
        cp -fv liblwjgl64.so ~/.minecraft/bin/natives
        cp -fv libopenal64.so ~/.minecraft/bin/natives
        cp -fv libjinput-linux.so ~/.minecraft/bin/natives
        cp -fv liblwjgl.so ~/.minecraft/bin/natives
        cp -fv libopenal.so ~/.minecraft/bin/natives
        cd
        echo ":: Removing temporary folder..."
        rm -r linuxmcinputfix_temp
        rm -r download
        echo "Done!"