#!/bin/bash

source Settings
echo "Copying Jar files..."
cp $PathToLWJG/jar/jinput.jar ~/.minecraft/bin
cp $PathToLWJG/jar/lwjgl.jar ~/.minecraft/bin
cp $PathToLWJG/jar/lwjgl_util.jar ~/.minecraft/bin
echo "Copied Jars!"
echo "Copying Natives..."
cd $PathToLWJG/native/linux
cp libjinput-linux.so libjinput-linux64.so liblwjgl.so liblwjgl64.so libopenal.so libopenal64.so ~/.minecraft/bin/natives
echo "Done Patching!"