#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $PWD
source $DIR/Settings
echo $ScriptLocation
echo "Welcome to my Alpha launcher!"
echo "What would you like to do?"
echo "Play | Patchlwjgl | Mod"
read quest
cd $ScriptLocation
if [ $quest == "Play" ] ; then
    echo $PathToLaunchers
    echo "Availible launchers"
    ls -f --color $PathToLaunchers
    echo "Which launcher would you like to use?"

    #checks input for Launcher
    read Launcher

    echo You have selected $Launcher !
    echo Starting Minecraft...

    #launches whatever was chosen
    java -jar $PathToLaunchers/$Launcher.jar
fi

if [ $quest == "Patchlwjgl" ] ; then
    Online()
    {
        cd
        echo ":: Creating temp folder..."
        mkdir linuxmcinputfix_temp
        cd linuxmcinputfix_temp
        echo ":: Downloading Lightweight java gaming library..."
        wget -nv http://downloads.sourceforge.net/project/java-game-lib/Official%20Releases/LWJGL%202.6/lwjgl-2.6.zip
        echo ":: Unzipping into temp folder..."
        unzip -q lwjgl*
        cd ~/linuxmcinputfix_temp/lwjgl-2.6/jar/
        echo ":: Copying files into Minecraft folder..."
        cp -fv jinput.jar ~/.minecraft/bin/
        cp -fv lwjgl.jar ~/.minecraft/bin/
        cp -fv lwjgl_util.jar ~/.minecraft/bin/

        cd ~/linuxmcinputfix_temp/lwjgl-2.6/native/linux/
        cp -fv libjinput-linux64.so ~/.minecraft/bin/natives
        cp -fv liblwjgl64.so ~/.minecraft/bin/natives
        cp -fv libopenal64.so ~/.minecraft/bin/natives
        cp -fv libjinput-linux.so ~/.minecraft/bin/natives
        cp -fv liblwjgl.so ~/.minecraft/bin/natives
        cp -fv libopenal.so ~/.minecraft/bin/natives
        cd
        echo ":: Removing temporary folder..."
        rm -r linuxmcinputfix_temp
        rm -r download
        echo "Done!"
    }

    Local()
    {
        source Settings
        echo "Copying Jar files..."
        cp $PathToLWJG/jar/jinput.jar ~/.minecraft/bin
        cp $PathToLWJG/jar/lwjgl.jar ~/.minecraft/bin
        cp $PathToLWJG/jar/lwjgl_util.jar ~/.minecraft/bin
        echo "Copied Jars!"
        echo "Copying Natives..."
        cd $PathToLWJG/native/linux
        cp libjinput-linux.so libjinput-linux64.so liblwjgl.so liblwjgl64.so libopenal.so libopenal64.so ~/.minecraft/bin/natives
        echo "Done Patching!"
    }

echo "Local or Online"
read PatchMethod
if [ $PatchMethod == "Online" ] ; then
    Online
fi
if [ $PatchMethod == "Local" ] ; then 
    Local
fi
fi

if [ $quest == "Mod" ] ; then 
    bash $ScriptLocation/ModManager
fi