#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $PWD
source $DIR/Settings
echo $ScriptLocation
echo "Welcome to my Alpha launcher!"
echo "What would you like to do?"
echo "Play | Patchlwjgl | Mod"
read quest
cd $ScriptLocation
if [ $quest == "Play" ] ; then
    bash $ScriptLocation/Launcher
fi

if [ $quest == "Patchlwjgl" ] ; then
    bash $ScriptLocation/lwjglOnline
fi

if [ $quest == "Mod" ] ; then 
    bash $ScriptLocation/ModManager
fi