#!/bin/bash
source Settings
source Mods

iChunInstaller ()
{
    echo "Which iChun mod would you like to install?"
    echo "BackTools, GravityGun, MobAmputation, MobDismemberment, PortalGun, Slender"
    read Mod
    if [ $Mod == "BackTools" ] ; then 
        wget http://www.creeperrepo.net/wget/61465c79ec54db70a97bea6243275980/files/BackTools1.5.2v1.zip
        mv BackTools*.zip ~/.minecraft/mods
    fi
    if [ $Mod == "MobAmputation" ] ; then 
        wget http://www.creeperrepo.net/wget/cf5a1920a963eeaf18ee8a18887313aa/files/MobAmputation1.5.2v1.zip
        mv MobAmputation*.zip ~/.minecraft/mods
    fi
    if [ $Mod == "MobDismemberment" ] ; then 
        wget http://www.creeperrepo.net/wget/77c9ccddbc9dc71a5086d104a153eb66/files/MobDismemberment1.5.2v1.zip
        mv MobDismemberment*.zip ~/.minecraft/mods
    fi
    if [ $Mod == "Slender" ] ; then 
        wget http://www.creeperrepo.net/wget/985c55e1460271f0b36ff46a7303fd95/files/Slender1.5.0.zip
        mv Slender*.zip ~/.minecraft/mods
    fi
}

OptiFineInstaller ()
{
  ls $PathToMods
  echo "Which mod would you like to be .jar installed?"
  ls --color $PathToMods
  read Mod
  mkdir $PathToMods/$Mod
  cp $PathToMods/$Mod.zip $PathToMods/$Mod
  cp ~/.minecraft/bin/minecraft.jar $PathToMods/$Mod
  cd $PathToMods/$Mod
  pwd
  unzip $PathToMods/$Mod/minecraft.jar
  unzip $PathToMods/$Mod/$Mod*
  rm -rf $PathToMods/$Mod/$Mod*.zip
  rm -rf $PathToMods/$Mod/minecraft.jar
  rm -rf META-INF
  zip -r $PathToMods/$Mod/minecraft.jar *
  cp $PathToMods/$Mod/minecraft.jar $PathToMods
  rm -rf $PathToMods/$Mod
#  mv $PathToMods/minecraft.jar $PathToMods/minecraftOptiFine.jar
  mv ~/.minecraft/bin/minecraft.jar ~/.minecraft/bin/minecraftBackup.jar
  cp $PathToMods/minecraft.jar ~/.minecraft/bin
  mv $PathToMods/minecraft.jar $PathToMods/minecraft$Mod.jar
}

Mod_Manager () {
ls --color $PathToMods
ls --color ~/.minecraft/mods
echo "Which mod would you like to add/delete?"
read Mod

echo "Would you like this to be added, or deleted? [Add] [Delete]"
read Operation


if [ $Operation == "Delete" ] ; then
    rm ~/.minecraft/mods/$Mod
    echo "Removed $Mod"
fi
echo "Continue Modding? [Y/N]"
read Modding
}

echo "Would you like to download, add Jar Install, or modloader install mods? You can also install iChun's mods [DL] [A] [I] [JI] [iChun]"
read Operation
if [ $Operation == "Add" ] ; then
    cp $PathToMods/$Mod ~/.minecraft/mods
    echo "added $Mod!"
fi 
if [ $Operation == "DL" ] ; then
    cat Mods
    echo "Which mod would you like to download?"
    read ModToDL
    wget --spider $ModToDL
#    wget -nv $ModToDL $PathToMods
    wget -U firefox -r -np $ModToDL
    mv $ModToDL $PathToMods
fi
if [ $Operation == "Add" ] ; then
    if [ $Modding="Y" ] ; then
        Mod_Manager
    fi
fi
if [ $Operation == "A" ] ; then
    echo "What is the Mod you would like to add?"
    read Mod
    echo "What is the download link for the mod?"
    read DLlink
    echo $Mod=$DLlink>>$ScriptLocation/Mods
fi
if [ $Operation == "JI" ] ; then
    OptiFineInstaller
fi
if [ $Operation == "JarInstall" ] ; then
    OptiFineInstaller
fi
if [ $Operation == "iChun" ] ; then
    iChunInstaller
fi


# wget --spider "downloadx.php?f=OptiFine_1.5.2_HD_D2.zip&amp;x=46db9389dcc31594dc9e6c5c97877d8d"
#
#

echo "Thank you for using Cheapshades97s ModManager!"
echo "Goodbye!"