#!/bin/bash
source Settings
source Mods
ModInstaller ()
{
    echo "Which mod would you like to move to the Mod folder?"
    ls --color $PathToMods
    read Mod
    cp $PathToMods/$Mod* ~/.minecraft/mods
}

ModUninstaller ()
{
    echo "Which mod would you like to uninstall?"
    ls --color ~/.minecraft/mods
    read Mod 
    rm -rf $Mod*
    echo "Mod Uninstalled!"
}

iChunInstaller ()
{
    echo "Which iChun mod would you like to install?"
    echo "BackTools, GravityGun, MobAmputation, MobDismemberment, PortalGun, Slender"
    read Mod
    if [ $Mod == "BackTools" ] ; then 
        wget http://www.creeperrepo.net/wget/61465c79ec54db70a97bea6243275980/files/BackTools1.5.2v1.zip
        cp BackTools*.zip ~/.minecraft/mods
    fi
    if [ $Mod == "MobAmputation" ] ; then 
        wget http://www.creeperrepo.net/wget/cf5a1920a963eeaf18ee8a18887313aa/files/MobAmputation1.5.2v1.zip
        cp MobAmputation*.zip ~/.minecraft/mods
    fi
    if [ $Mod == "MobDismemberment" ] ; then 
        wget http://www.creeperrepo.net/wget/77c9ccddbc9dc71a5086d104a153eb66/files/MobDismemberment1.5.2v1.zip
        cp MobDismemberment*.zip ~/.minecraft/mods
    fi
    if [ $Mod == "Slender" ] ; then 
        wget http://www.creeperrepo.net/wget/985c55e1460271f0b36ff46a7303fd95/files/Slender1.5.0.zip
        cp Slender*.zip ~/.minecraft/mods
    fi
    echo "Would you like to keep the mod installed locally? Y/N"
    read StoreLocally
        if [ $StoreLocally == "Y" ] ; then 
            echo "Thank you for using my mod manager!"
        fi
        
        if [ $StoreLocally == "N" ] ; then
            rm -rf $Mod*
            echo "Thank you for using my mod manager!"
        fi
}

OptiFineInstaller ()
{
    ls $PathToMods
    echo "Which mod would you like to be .jar installed?"
    ls --color $PathToMods
    read Mod
    mkdir $PathToMods/$Mod
    cp $PathToMods/$Mod.zip $PathToMods/$Mod
    cp ~/.minecraft/bin/minecraft.jar $PathToMods/$Mod
    cd $PathToMods/$Mod
    pwd
    unzip $PathToMods/$Mod/minecraft.jar
    unzip $PathToMods/$Mod/$Mod*
    rm -rf $PathToMods/$Mod/$Mod*.zip
    rm -rf $PathToMods/$Mod/minecraft.jar
    rm -rf META-INF
    zip -r $PathToMods/$Mod/minecraft.jar *
    cp $PathToMods/$Mod/minecraft.jar $PathToMods
    rm -rf $PathToMods/$Mod
    #  mv $PathToMods/minecraft.jar $PathToMods/minecraftOptiFine.jar
    mv ~/.minecraft/bin/minecraft.jar ~/.minecraft/bin/minecraftBackup.jar
    cp $PathToMods/minecraft.jar ~/.minecraft/bin
    mv $PathToMods/minecraft.jar $PathToMods/minecraft$Mod.jar
}

ModAdder ()
{
    echo "What is the Mod you would like to add?"
    read Mod
    echo "What is the download link for the mod?"
    read DLlink
    echo $Mod=$DLlink>>$ScriptLocation/Mods
}

Mod_Manager () 
{
    echo "Downloaded Mods"
    ls --color $PathToMods
    echo "~~~~~~~~~~~~~~"
    echo "Mods Installed"
    ls --color ~/.minecraft/mods
    echo "What sort of modding would you like to do?"
    echo "Uninstall a mod [Uninstall] [ModloaderInstall] [JarInstall] [DownloadAndInstall] [Add]"
    read Operation


        if [ $Operation == "Uninstall" ] ; then
            ModUninstaller
        fi
        
        if [ $Operation == "ModloaderInstall" ] ; then
            ModInstaller
        fi
        
        if [ $Operation == "JarInstall" ] ; then
            OptiFineInstaller
        fi
        
        if [ $Operation == "DownloadAndInstall" ] ; then
            iChunInstaller
        fi
        
        if [ $Operation == "Add" ] ; then 
            ModAdder
        fi

}
Mod_Manager
echo "Thank you for using Cheapshades97s ModManager!"
echo "Goodbye!"