#!/bin/bash
source Settings


ServerSetup ()
{
    cd
    echo "What would you like the server name to be?"
    read ServerName
    echo "Where are your servers saved?"
    echo "Please use /home/user/ Formating"
    read ServerLocation
    cd $ServerLocation
    mkdir $ServerName
    ls $ServerLocation
    wget https://s3.amazonaws.com/MinecraftDownload/launcher/minecraft_server.jar
    mv minecraft_server.jar $ServerLocation/$ServerName
    ls $ServerLocation
    pwd
    echo "::Now running initial setup of server::"
    cd $ServerLocation/$ServerName
    java -jar $ServerLocation/$ServerName/minecraft_server.jar
}

ServerStart ()
{
   echo "Test" 
}

echo "What would you like to do? [Setup]"
read Operation

    if [ $Operation == "Setup" ] ; then 
        ServerSetup
    fi