#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/Settings

ServerSetup ()
{
    cd
    echo "What would you like the server name to be?"
    read ServerName
#    echo "Where are your servers saved?"
#    echo "Please use /home/user/ Formating"
#    read ServerLocation
    cd $ServerLocation
    mkdir $ServerName
    ls $ServerLocation
    wget https://s3.amazonaws.com/MinecraftDownload/launcher/minecraft_server.jar
    mv minecraft_server.jar $ServerLocation/$ServerName
    ls $ServerLocation
    pwd
    echo "::Now running initial setup of server::"
    cd $ServerLocation/$ServerName
    java -jar $ServerLocation/$ServerName/minecraft_server.jar
}

ServerStart ()
{
   echo "Which Server would you like to start?"
   ls $ServerLocation
   read Server
   cd $ServerLocation/$ServerName
   java -jar $ServerLocation/$Server/minecraft_server.jar
}

echo "What would you like to do? [Setup] [Start]"
read Operation

    if [ $Operation == "Setup" ] ; then 
        ServerSetup
    fi
    if [ $Operation == "Start" ] ; then
        ServerStart
    fi