#!/bin/bash

sudo echo "Welcome to the Launcher Selector!"
echo "Created by Cheapshades97"

echo "What is the path to your Minecraft launchers?"
read "PathToLaunchers"

echo "adding Alias..."
echo alias Minecraft=$PWD/Minecraft>> ~/.bashrc 

echo "Would you like to set the path to a local update of lwjgl? [Yes] [No]"
read SetPath
if [ $SetPath == "Yes" ] ; then
    echo "What is the path to your local lwjgl?"
    read PathToLWJG
fi

echo "What is the path to your downloaded mods?"
read PathToMods

cat > Settings << EOF
PathToLaunchers=$PathToLaunchers
PathToLWJG=$PathToLWJG
PathToMods=$PathToMods
ScriptLocation=$PWD
EOF

chmod 755 Settings

echo "Restart Terminal and type Minecraft to use the Selector!"